all:
	fstar.exe Incr.fst
	fstar.exe Sum.fst
	fstar.exe RefinedStackLength.fst
	fstar.exe RefinedStackLengthClient.fst
	fstar.exe SumST.fst
	fstar.exe --z3rlimit_factor 5 RSA.fst
	fstar.exe InitFreezeMST.fst
